### ISSUE TITLE
多仓库格式支持

### ISSUE THREAD

**Issue by 8080713** [mlabalabala/BBox#2]
https://raw.liucn.cc/box/dm.txt
什么时候可以支持这样的格式呢

**Comment by mlabalabala** [comment]
在处理多仓的时候，默认取第一条里面的线路内容作为历史记录添加的，本来是想的有几条网络线路能用就行，切换的时候方便。处理https://raw.liucn.cc/box/dm.txt这种格式的app其实有很多大佬的修改版本已经实现了，目前还没有打算去处理多仓的所有线路。不好意思哈从(～￣▽￣)～

**Comment by mlabalabala** [comment]
在处理多仓的时候，默认取第一条里面的线路内容作为历史记录添加的，本来是想的有几条网络线路能用就行，切换的时候方便。处理[https://raw.liucn.cc/box/dm.txt](https://raw.liucn.cc/box/dm.txt)这种格式的app其实有很多大佬的修改版本已经实现了，目前还没有打算去处理多仓的所有线路。不好意思哈从(～￣▽￣)～

**Comment by mlabalabala** [comment]
简单修改了一下多源的逻辑，可以再多源历史里进行切换，，，emmm   具体使用有问题或者影响使用的话  还是用大佬的修改版本把

**Comment by 8080713** [comment]
等着你更新新功能
